version: '3.5'

services:
  discord-bot:
    build:
      context: .
    environment:
      POSTGRES_SERVICE: db-users:5432

  db-postgres:
    image: postgres:14.5-alpine
    volumes:
      - usersdb:/var/lib/postgresql/data
    ports:
      - '15444:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  usersdb:
